----
#### 특성(Feature) 공학과 규제(Regularization : 정형화, 일반화, 규제)


In [34]:
import pandas as pd

In [35]:
df = pd.read_csv("../Data/fish.csv")
df.head()

,length,height,width
0,8.4,2.11,1.41
1,13.7,3.53,2.00
2,15.0,3.82,2.43
3,16.2,4.59,2.63
4,17.4,4.59,2.94


In [36]:
fish_full = df.to_numpy()

In [37]:
df = pd.read_csv("../Data/fish_weight.csv")
df.head()


,weight
0,5.9
1,32.0
2,40.0
3,51.5
4,70.0


In [38]:
fish_weight = df.to_numpy()
fish_weight[:5]

array([[ 5.9],
       [32. ],
       [40. ],
       [51.5],
       [70. ]])

In [39]:
# Train과 Test
from sklearn.model_selection import train_test_split

In [40]:
train_input, test_input, train_target, test_target = \
   train_test_split(
      fish_full,
      fish_weight,
      random_state=42

   )

#### sklearn으로 다중회귀 분석하기

In [41]:
from sklearn.preprocessing import PolynomialFeatures

In [42]:
# 다항 특성 만들기

poly = PolynomialFeatures(include_bias=False)
poly.fit([[2,3]])
poly.transform([[2,3]])

array([[2., 3., 4., 6., 9.]])

In [43]:

poly = PolynomialFeatures(include_bias=False) # degree = 2
poly.fit([[2,3]])
poly.transform([[2,3]])

array([[2., 3., 4., 6., 9.]])

In [44]:
poly.get_feature_names_out()

array(['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2'], dtype=object)

----
#### 다향 특성 만들기

In [45]:
train_input.shape

(42, 3)

In [46]:
# train_input을 다항 특성 만들기
poly = PolynomialFeatures(include_bias=False)
train_poly = poly.fit_transform(train_input)

In [47]:
train_input.shape

(42, 3)

In [48]:
# 컬럼 정보 확인
poly.get_feature_names_out()

array(['x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2',
       'x2^2'], dtype=object)

In [49]:
train_poly[:5]

array([[  19.6   ,    5.14  ,    3.04  ,  384.16  ,  100.744 ,   59.584 ,
          26.4196,   15.6256,    9.2416],
       [  22.    ,    5.88  ,    3.52  ,  484.    ,  129.36  ,   77.44  ,
          34.5744,   20.6976,   12.3904],
       [  18.7   ,    5.2   ,    3.12  ,  349.69  ,   97.24  ,   58.344 ,
          27.04  ,   16.224 ,    9.7344],
       [  17.4   ,    4.59  ,    2.94  ,  302.76  ,   79.866 ,   51.156 ,
          21.0681,   13.4946,    8.6436],
       [  36.    ,   10.61  ,    6.74  , 1296.    ,  381.96  ,  242.64  ,
         112.5721,   71.5114,   45.4276]])

In [50]:
# test_input도 다항특성 만들기
test_poly = poly.transform(test_input)
test_poly.shape

(14, 9)

#### 다중 회귀 모델 훈련하기

In [51]:
from sklearn.linear_model import LinearRegression

In [52]:
lr = LinearRegression()
lr.fit(train_input, train_target)
print("Train :", lr.score(train_input, train_target))
print("Test :", lr.score(test_input, test_target))

Train : 0.9559326821885706
Test : 0.8796419177546368


In [53]:
# 위의 것보다 결과값이 더 좋아짐

lr = LinearRegression()
lr.fit(train_poly, train_target)
print("Train :", lr.score(train_poly, train_target))
print("Test :", lr.score(test_poly, test_target))

Train : 0.9903183436982124
Test : 0.9714559911594134


----
#### 더 많은 특성 만들기

In [54]:
poly = PolynomialFeatures(include_bias=False, degree=5)
poly.fit(train_input)
train_poly = poly.transform(train_input)
test_poly = poly.transform(test_input)

In [55]:
poly.get_feature_names_out()

array(['x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2',
       'x2^2', 'x0^3', 'x0^2 x1', 'x0^2 x2', 'x0 x1^2', 'x0 x1 x2',
       'x0 x2^2', 'x1^3', 'x1^2 x2', 'x1 x2^2', 'x2^3', 'x0^4', 'x0^3 x1',
       'x0^3 x2', 'x0^2 x1^2', 'x0^2 x1 x2', 'x0^2 x2^2', 'x0 x1^3',
       'x0 x1^2 x2', 'x0 x1 x2^2', 'x0 x2^3', 'x1^4', 'x1^3 x2',
       'x1^2 x2^2', 'x1 x2^3', 'x2^4', 'x0^5', 'x0^4 x1', 'x0^4 x2',
       'x0^3 x1^2', 'x0^3 x1 x2', 'x0^3 x2^2', 'x0^2 x1^3',
       'x0^2 x1^2 x2', 'x0^2 x1 x2^2', 'x0^2 x2^3', 'x0 x1^4',
       'x0 x1^3 x2', 'x0 x1^2 x2^2', 'x0 x1 x2^3', 'x0 x2^4', 'x1^5',
       'x1^4 x2', 'x1^3 x2^2', 'x1^2 x2^3', 'x1 x2^4', 'x2^5'],
      dtype=object)

In [56]:
lr.fit(train_poly,train_target)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](1, 55)","[[-0. ,-0. ,-0. ,..., 0. , 0.02, 0.02]]"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.","ndarray[float64](1,)",[20.02]
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,55
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(13)
"singular_ singular_: array of shape (min(X, y),)Singular values of `X`. Only available when `X` is dense.","ndarray[float64](42,)","[3.29e+08,6.78e+06,3.28e+06,...,7.31e-04,2.49e-04,3.65e-08]"


In [65]:

print("Train : ", lr.score(train_poly, train_target))
print("Test : ", lr.score(test_poly, test_target))

# 원래는 해당 test의 값이 음수로 나와야함

Train :  0.9953852031717483
Test :  0.9780184172675365


In [58]:
train_poly.shape

(42, 55)

#### 규제
모델이 과적합되게 학습하지 않고 일반성을 가질 수 있도록 규제(정규화)하는 것

In [59]:
# 규제 전에 표준화
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_poly)

train_scaled = ss.transform(train_poly)
test_scaled = ss.transform(test_poly)


#### Ridge(L2규제)
: 가중치의 제곱으로 규제하는 방법이다

In [60]:
from sklearn.linear_model import Ridge

In [61]:
ridge = Ridge()
ridge.fit(train_scaled,train_target )
print("Train : ", ridge.score(train_scaled,train_target))
print("test : ", ridge.score(test_scaled,test_target))

Train :  0.9896101671037343
test :  0.9790693977615386


#### 적절한 규제 강도(Hyper parameter) 찾기

In [62]:
train_score = []
test_score = []
alpha_list = [0.001,0.01,0.1,1,10,100] # 임의로 정한다

for alpha in alpha_list:
   ridge = Ridge(alpha=alpha)
   ridge.fit(train_scaled, train_target)
   train_score.append(ridge.score(train_scaled, train_target))
   test_score.append(ridge.score(test_scaled, test_target))

In [63]:
pd.DataFrame(
   {
      'Train ': train_score,
      'Test' : test_score
   }
)

,Train,Test
0,0.993046,0.956939
1,0.991781,0.980019
2,0.990382,0.982798
3,0.989610,0.979069
4,0.988728,0.972533
5,0.984184,0.962704


In [64]:
ridge = Ridge(alpha=0.1) #default : alpha = 1
ridge.fit(train_scaled,train_target )
print("Train : ", ridge.score(train_scaled,train_target))
print("test : ", ridge.score(test_scaled,test_target))

Train :  0.9903815817570369
test :  0.9827976465386986
