# 인덱싱(Indexing)

- ndArray에서 데이터를 검색하는 방법
- 인덱싱 방법
|종류|방법|특징
|----|----|----|
|단일값 인덱싱|arr[2]|특정위치 단일값 출력|
|슬라이싱|arr[1:4]|연속된 범위|
|팬시인덱싱|arr[0, 2, 4]|불연속 위치 다중값 출력|
|불린인덱싱|arr[arr > 5]|조건에 맞는 값 출력|

## (1) 단일값 인덱싱

In [2]:
import numpy as np

In [3]:
# 1~9까지 ndarray 데이터 생성
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 2번지의 데이터 출력
arr[2]

np.int64(3)

In [6]:
# 인덱스 별 단일 값 출력
print(arr[0], arr[-1], arr[4])

1 9 5


## (2) 단일값 인덱싱을 통한 데이터 변경

In [8]:
arr[0] = 100
print(arr)
arr[-1] = 900
print(arr)

[100   2   3   4   5   6   7   8   9]
[100   2   3   4   5   6   7   8 900]


- 2차원 배열은 arr[row, col]로 접근

In [9]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# 3행 3열의 2차원 배열로 반환
arr2 = arr.reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# 출력
arr2.shape
print(arr2[0,2], arr2[2,1], arr2[-1, -1])

3 8 9


## (4) 슬라이싱

- ':' 기호를 이용ㅎ여 연속된 데이터를 출력

In [21]:
array1 = np.arange(1, 10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# 0, 1, 2 세개의 데이터 출력
print(array1[0:3])

[1 2 3]


In [24]:
array1[3:-1]

array([4, 5, 6, 7, 8])

In [37]:
# [4,5,6]
print(array1[3:6])

# [1,2,3]
print(array1[0:3])

# [1,3,5,7,9]
print(array1[::2])                # start, end 생략 시 맨처음 / 맨끝

# [9,8,7,6,...,1] 역순으로 출력
print(array1[::-1])

# 마지막 데이터 3개 출력
print(array1[-3:])

[4 5 6]
[1 2 3]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]
[7 8 9]


- 2차원 슬라이싱 : [행 범위, 컬럼 범위]

In [41]:
# 3행 3열의 2차원 배열 생성 : 데이터는 1~9
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
print(arr[0:2, 0:2])

[[1 2]
 [4 5]]


## (5) 팬시 인덱싱
- 불연속적인 여러 위치의 값을 인덱싱하여 출력

- 1차원 배열의 팬시 인덱싱

In [43]:
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
print(arr1[[0, 2, 3]])       # 인덱스 번호를 통해 불연속적 값에 접근

[1 3 4]


In [54]:
# 슬라이싱 + 팬시 인덱싱
value = arr1[4:][[2,4]]
print(value, value.shape)

[7 9] (2,)


- 2차원 배열 팬시 인덱싱

In [55]:
# (3, 3), 1~9
arr2 = np.arange(1,10).reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
# [[행], [열]]
print(arr2[[0, 1], [0, 2]])           # (0,0), (1,2) 인덱스 가진 값들 출력
print(arr2[[0,1], 2])                 # (0,2), (1,2)
print(arr2[[0,2], 1:2])

[1 6]
[3 6]
[[2]
 [8]]


## (6) 불린 인덱싱

- 조건식을 사용하여 인덱싱
- 데이터 필터링에 자주 사용

In [64]:
arr3 = np.arange(1,10)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
# 1차원 배열의 데이터 중 4보다 큰 데이터만 출력
arr3[arr3 > 4]

array([5, 6, 7, 8, 9])

In [69]:
# 불린 인덱싱은 내부적으로 조건에 맞는 불린값으로 필터링 실행 후 
# True인 값만 출력
arr3_bool = arr3 < 5
arr3_bool

array([ True,  True,  True,  True, False, False, False, False, False])

In [73]:
# 짝수 값만 출력
arr3[arr3%2 == 0]

# 2의 배수 또는 5의 배수 출력          ( | : or연산, & : and 연산 )
arr3[(arr3%2 == 0) | (arr3%5 == 0)]

array([2, 4, 5, 6, 8])

- 불린인덱싱 vs for 루프

In [81]:
arr = np.arange(1,10)
arr[ arr > 5]

array([6, 7, 8, 9])

In [82]:
# for 루프 => [6, 7, 8, 9]
target = []
for i in range(1, len(arr)+1) :
    if i > 5 :
        target.append(i)

target

[6, 7, 8, 9]

In [86]:
# 학생 성적 데이터에서 80점 이상 학생 이름 추출
names = np.array(['홍길동', '김유신', '강감찬', '이순신', '스미스'])
score = np.array([72, 81, 95, 89, 88])

# 80점 이상인 학생 이름 출력
print(names[score >= 80])
# 80점 이상인 점수 출력
print(score[score >= 80])

['김유신' '강감찬' '이순신' '스미스']
[81 95 89 88]
