# 배열 연산
- 배열의 shape이 같으면 데이터별로 연산이 진행됨

In [1]:
import numpy as np

In [5]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1, arr2)

[1 2 3] [4 5 6]


In [6]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


- 스칼라(단일 숫자)와 연산

In [8]:
print(arr1 + 10)
print(arr1 - 10)
print(arr1 * 10)
print(arr1 / 10)

[11 12 13]
[-9 -8 -7]
[10 20 30]
[0.1 0.2 0.3]


- 2차원 배열 연산

In [9]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(arr1.shape, arr2.shape)

(2, 2) (2, 2)


In [10]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


## 정렬 - sort() 와 argsort()

### (1) sort()
- numpy.sort() vs numpy.ndarray.sort() : 원본 배열의 유지 여부가 핵심
- 원본 유지 O : numpy.sort()
- 원본 유지 X : numpy.ndarray.sort()

In [14]:
org_arr = np.array([2, 1, 3, 6, 9])
org_arr

array([2, 1, 3, 6, 9])

In [16]:
# 오름 차순 정렬 후 새 배열 반환
sort_arr = np.sort(org_arr)
sort_arr

array([1, 2, 3, 6, 9])

In [17]:
print(org_arr, sort_arr)

[2 1 3 6 9] [1 2 3 6 9]


In [18]:
# 원본 배열을 직접 오름차순 정렬
org_arr.sort()
org_arr

array([1, 2, 3, 6, 9])

- 내림차순 정렬 : 배열[ : : -1]

In [22]:
org_arr = np.array([8, 4, 9, 2, 5])
sort_arr = np.sort(org_arr)[::-1]
sort_arr

array([9, 8, 5, 4, 2])

In [24]:
org_arr = np.array([8, 4, 9, 2, 5])
org_arr.sort()
org_arr[::-1]
org_arr

array([2, 4, 5, 8, 9])

- 2차원 배열 정렬

In [25]:
arr = np.array([[8, 12],
               [7, 1]])
arr

array([[ 8, 12],
       [ 7,  1]])

In [32]:
# axis = 0 : row 기준 정렬(세로축 비교) / axis = 1 : col 기준 정렬(가로축 비교)
sort_arr1 = np.sort(arr, axis = 0)
sort_arr2 = np.sort(arr, axis = 1)
print(sort_arr1, sort_arr2, sep='\n')

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


### (2) argsort()

- 정렬된 인덱스 반환

In [34]:
names = np.array(['홍길동', '김유신', '강감찬', '이순신', '스미스'])
score = np.array([72, 81, 95, 66, 88])

In [37]:
# 성적순으로 names 배열을 오름차순 정렬
idx = np.argsort(score)
target = []

for i in idx:
    target.append(str(names[i]))

target

['이순신', '홍길동', '김유신', '스미스', '강감찬']

In [39]:
names[idx]        # 팬시 인덱싱

array(['이순신', '홍길동', '김유신', '스미스', '강감찬'], dtype='<U3')

In [41]:
# 성적순으로 names 배열을 내림차순 정렬
idx = np.argsort(score)[::-1]
names[idx]

array(['강감찬', '스미스', '김유신', '홍길동', '이순신'], dtype='<U3')

# 집계 함수

In [42]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
print(np.sum(arr))    # 합계
print(np.mean(arr))   # 평균
print(np.min(arr))    # 최소
print(np.max(arr))    # 최대
print(np.std(arr))    # 표준편차
print(np.var(arr))    # 분산
print(np.median(arr))    # 중앙값

45
5.0
1
9
2.581988897471611
6.666666666666667
5.0
